apiVersion: v1
kind: Secret
metadata:
  name: sc-secret
  annotations:
    tekton.dev/docker-0: https://docker.io
type: kubernetes.io/basic-auth
stringData:
  username: ""
  password: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sc-account
secrets:
  - name: sc-secret