---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
  labels:
    app.kubernetes.io/version: {{ .Chart.Version }}
{{- if .Values.annotations }}
  annotations:
  {{- .Values.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  description: |
    Buildah task builds source into a container image and
    then pushes it to a container registry.
  params:
    - name: IMAGE
      type: string
      description: |
        Reference of the image buildah will produce.
    - name: REGISTRY
      type: string
      description: |
        Full qualified registry url, including image name
    - name: STORAGE_DRIVER
      type: string
      default: overlay
      description: |
        Set buildah storage driver
    - name: CONTAINERFILE_PATH
      type: string
      default: ./Containerfile
      description: |
        Path to the `Containerfile` (`Dockerfile`) to build.
    - name: CONTEXT_SUBDIRECTORY
      type: string
      default: .
      description: |
        Relative subdirectory to the `source` Workspace used as "context".
    - name: TLS_VERIFY
      type: string
      default: "true"
      description: |
        Sets the TLS verification flags, `true` is recommended.
    - name: BUILD_EXTRA_ARGS
      type: string
      default: ""
      description: |
        Extra parameters passed for the build command when building images.
    - name: PUSH_EXTRA_ARGS
      type: string
      default: ""
      description: |
        Extra parameters passed for the push command when pushing images.
    - name: SKIP_PUSH
      default: "false"
      description: |
        Skip pushing the built image
    - name: VERBOSE
      type: string
      default: "false"
      description:
        Turns on verbose logging, all commands executed will be printed out.

  workspaces:
    - name: source
      optional: true
      description: |
        Application source-code. Will contain the Container File.

  results:
    - name: IMAGE_DIGEST
      description: |
        Digest of the image just built.
    - name: IMAGE_METADATA
      description: |
        Contains Metadata of the digest
    - name: IMAGE_URL
      description: |
        Image repository where the built image would be pushed to
  
  stepTemplate:
    env:
{{- $variables := list
      "params.IMAGE"
      "params.REGISTRY"
      "params.STORAGE_DRIVER"
      "params.TLS_VERIFY"
      "params.CONTAINERFILE_PATH"
      "params.CONTEXT_SUBDIRECTORY"
      "params.BUILD_EXTRA_ARGS"
      "params.PUSH_EXTRA_ARGS"
      "params.SKIP_PUSH"
      "params.VERBOSE"
      "workspaces.source.path"
      "workspaces.source.bound"
      "results.IMAGE_DIGEST.path"
      "results.IMAGE_METADATA.path"
      "results.IMAGE_URL.path"
}}
{{- include "environment" ( list $variables ) | nindent 6 }}

  steps:
{{- include "load_scripts" ( list . "buildah-" ) | nindent 4 }}
    - name: build
      image: {{ .Values.images.buildah }}
      command:
        - /scripts/buildah-bud-push.sh
      volumeMounts:
        - name: scripts-dir
          mountPath: /scripts
      securityContext:
        privileged: true
    - name: buildah-results
      image: {{ .Values.images.buildah }}
      command:
        - /scripts/buildah-results.sh
      volumeMounts:
        - name: scripts-dir
          mountPath: /scripts

  volumes:
  - name: scripts-dir
    emptyDir: {}
      
